# Generated by Django 5.1.7 on 2026-04-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ten danh muc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mo ta')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kich hoat')),
            ],
            options={
                'verbose_name': 'Danh muc',
                'verbose_name_plural': 'Danh muc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ten san pham')),
                ('author', models.CharField(max_length=100, verbose_name='Thuong hieu')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(verbose_name='Mo ta')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Gia')),
                ('discount', models.DecimalField(decimal_places=0, default=0.0, max_digits=5, verbose_name='Giam gia (%)')),
                ('stock', models.IntegerField(verbose_name='So luong ton kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='snacks/', verbose_name='Hinh anh')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='snacks.category', verbose_name='Danh muc')),
            ],
            options={
                'verbose_name': 'San pham',
                'verbose_name_plural': 'San pham',
                'ordering': ['title'],
                'db_table': 'snacks_book',
            },
        ),
    ]