# Generated by Django 5.0.14 on 2026-05-05 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='So sao')),
                ('comment', models.TextField(verbose_name='Noi dung danh gia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hien thi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='snacks.snack', verbose_name='San pham')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung')),
            ],
            options={
                'verbose_name': 'Danh gia san pham',
                'verbose_name_plural': 'Danh gia san pham',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('snack', 'user'), name='unique_review_per_user_snack'),
        ),
    ]
