# Generated by Django 5.0.14 on 2026-05-18 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_homecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá sản phẩm', 'verbose_name_plural': 'Đánh giá sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ['title'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Nội dung đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='review',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='snacks.snack', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='snacks.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5, verbose_name='Giảm giá (%)'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snacks/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='stock',
            field=models.IntegerField(verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
    ]
