# Generated by Django 5.1.7 on 2026-04-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snacks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ho va ten')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='So dien thoai')),
                ('address', models.TextField(verbose_name='Dia chi')),
                ('city', models.CharField(max_length=100, verbose_name='Tinh/Thanh pho')),
                ('district', models.CharField(max_length=100, verbose_name='Quan/Huyen')),
                ('ward', models.CharField(max_length=100, verbose_name='Phuong/Xa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chu')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tong tien hang')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phi van chuyen')),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('processing', 'Dang xu ly'), ('shipping', 'Dang giao'), ('completed', 'Hoan thanh'), ('cancelled', 'Da huy')], default='pending', max_length=20, verbose_name='Trang thai')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toan khi nhan hang')], default='cod', max_length=20, verbose_name='Phuong thuc thanh toan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khach hang')),
            ],
            options={
                'verbose_name': 'Don hang',
                'verbose_name_plural': 'Don hang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_name', models.CharField(max_length=200, verbose_name='Ten san pham')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='So luong')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Don gia')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Don hang')),
                ('snack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='snacks.snack', verbose_name='San pham')),
            ],
            options={
                'verbose_name': 'Chi tiet don hang',
                'verbose_name_plural': 'Chi tiet don hang',
            },
        ),
    ]