# Generated by Django 5.0.14 on 2026-05-05 02:54

import django.db.models.deletion
from django.db import migrations, models


def create_default_promotions(apps, schema_editor):
    Promotion = apps.get_model('orders', 'Promotion')
    Promotion.objects.get_or_create(
        code='SNACK10',
        defaults={
            'description': 'Giam 10% cho don hang',
            'discount_type': 'percent',
            'value': 10,
            'min_order_amount': 0,
            'max_discount_amount': 30000,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('snacks', '0002_review_review_unique_review_per_user_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Ma giam gia')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mo ta')),
                ('discount_type', models.CharField(choices=[('percent', 'Giam theo phan tram'), ('fixed', 'Giam so tien co dinh')], default='percent', max_length=20, verbose_name='Kieu giam gia')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Gia tri giam')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Gia tri don hang toi thieu')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Muc giam toi da')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay bat dau')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay ket thuc')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='So luot su dung')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Da su dung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kich hoat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
            ],
            options={
                'verbose_name': 'Ma giam gia',
                'verbose_name_plural': 'Ma giam gia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_default_promotions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tien giam'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ma giam gia da dung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=100, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí vận chuyển'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ward',
            field=models.CharField(max_length=100, verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='snacks.snack', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snack_name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promotion', verbose_name='Ma giam gia'),
        ),
    ]
