# Generated by Django 5.0.14 on 2026-05-18 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promotion_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mã giảm giá', 'verbose_name_plural': 'Mã giảm giá'},
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền giảm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promotion', verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mã giảm giá đã dùng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Giảm theo phần trăm'), ('fixed', 'Giảm số tiền cố định')], default='percent', max_length=20, verbose_name='Kiểu giảm giá'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức giảm tối đa'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn hàng tối thiểu'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượt sử dụng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm'),
        ),
    ]
